import{renderMazePage}from"../modules/maze-page-renderer.js";
import{drawTracingPage}from"../modules/tracing.js";
import{drawLogicPage}from"../modules/logic.js";

function drawColoring(canvas,page){const ctx=canvas.getContext("2d"),w=canvas.width,h=canvas.height,scale=w/180;ctx.fillStyle="#fff";ctx.fillRect(0,0,w,h);ctx.fillStyle="#111827";ctx.textAlign="center";ctx.font=`700 ${Math.max(11,11*scale)}px Arial`;ctx.fillText((page.title||"Coloring Page").slice(0,60),w/2,19*scale);const data=page.asset?.data;if(!data)return;const img=new Image();img.onload=()=>{const settings=page.settings||{},assetScale=(Number(settings.scale)||100)/100,maxW=w*.72,maxH=h*.72,ratio=Math.min(maxW/img.width,maxH/img.height)*assetScale,dw=img.width*ratio,dh=img.height*ratio,x=(w-dw)/2+(Number(settings.x)||0)*scale/5,y=32*scale+(h-42*scale-dh)/2+(Number(settings.y)||0)*scale/5;ctx.drawImage(img,x,y,dw,dh)};img.src=data}
function drawFallback(canvas,page){const ctx=canvas.getContext("2d");ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#64748b";ctx.textAlign="center";ctx.font=`700 ${Math.max(14,canvas.width/13)}px Arial`;ctx.fillText(page.title||"Strona",canvas.width/2,canvas.height/2)}
function drawSavedPreview(canvas,page){const data=page?.recipe?.meta?.previewImage;if(!data)return false;const ctx=canvas.getContext("2d"),img=new Image();ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);img.onload=()=>{ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height)};img.onerror=()=>renderGenerated(canvas,page);img.src=data;return true}
function renderGenerated(canvas,page){if(page.module==="maze-studio")renderMazePage(canvas,page);else if(page.module==="coloring-studio")drawColoring(canvas,page);else if(page.module==="tracing-studio")drawTracingPage(canvas,page);else if(page.module==="logic-studio")drawLogicPage(canvas,page);else drawFallback(canvas,page)}
function render(canvas,page,width,height,label){if(!canvas)return;canvas.width=width;canvas.height=height;canvas.setAttribute("aria-label",`${label}: ${page.title||"strona"}`);try{if(!drawSavedPreview(canvas,page))renderGenerated(canvas,page)}catch(error){console.error("Page render failed",error,page);drawFallback(canvas,page)}}
export function renderPageThumbnail(canvas,page){render(canvas,page,180,233,"Miniatura")}
export function renderPagePreview(canvas,page){render(canvas,page,900,1165,"Podgląd strony")}
