import{buildMaze,drawEndpointMarkers}from"../modules/maze-engine.js";
import{buildThemeDecorations,drawMazeTheme,normalizeTheme}from"../modules/maze-themes.js";
import{drawTracingPage}from"../modules/tracing.js";
import{drawLogicPage}from"../modules/logic.js";

function drawMaze(canvas,page){const ctx=canvas.getContext("2d"),settings=page.settings||{},cols=Math.max(6,Number(settings.cols)||18),rows=Math.max(8,Number(settings.rows)||24),maze=buildMaze(cols,rows,Number(page.seed)||1,settings.endpoints),theme=normalizeTheme(settings.theme),decorations=Array.isArray(settings.decorations)?settings.decorations:buildThemeDecorations({seed:page.seed,theme,count:settings.assetCount??6}),w=canvas.width,h=canvas.height,scale=w/180,margin=14*scale,top=31*scale,areaW=w-margin*2,areaH=h-top-margin,cell=Math.min(areaW/cols,areaH/rows),mazeW=cell*cols,mazeH=cell*rows,startX=(w-mazeW)/2,startY=top+(areaH-mazeH)/2;ctx.clearRect(0,0,w,h);ctx.fillStyle="#fff";ctx.fillRect(0,0,w,h);ctx.fillStyle="#111827";ctx.textAlign="center";ctx.font=`700 ${Math.max(11,11*scale)}px Arial`;ctx.fillText((page.title||"Maze").slice(0,60),w/2,18*scale);drawMazeTheme(ctx,{maze,startX,startY,cell,canvasWidth:w,canvasHeight:h,theme,decorations,compact:scale<2});ctx.strokeStyle="#111827";ctx.lineWidth=Math.max(1,Math.min(12,(Number(settings.lineWidth)||5)*scale/3));ctx.beginPath();for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const px=startX+x*cell,py=startY+y*cell,walls=maze.cells[y][x].w;if(walls[0]){ctx.moveTo(px,py);ctx.lineTo(px+cell,py)}if(walls[1]){ctx.moveTo(px+cell,py);ctx.lineTo(px+cell,py+cell)}if(walls[2]){ctx.moveTo(px,py+cell);ctx.lineTo(px+cell,py+cell)}if(walls[3]){ctx.moveTo(px,py);ctx.lineTo(px,py+cell)}}ctx.stroke();theme==="classic"?drawEndpointMarkers(ctx,maze,startX,startY,cell,scale<2):drawMazeTheme(ctx,{maze,startX,startY,cell,canvasWidth:w,canvasHeight:h,theme,decorations:[],compact:scale<2})}

function drawColoring(canvas,page){const ctx=canvas.getContext("2d"),w=canvas.width,h=canvas.height,scale=w/180;ctx.fillStyle="#fff";ctx.fillRect(0,0,w,h);ctx.fillStyle="#111827";ctx.textAlign="center";ctx.font=`700 ${Math.max(11,11*scale)}px Arial`;ctx.fillText((page.title||"Coloring Page").slice(0,60),w/2,19*scale);const data=page.asset?.data;if(!data)return;const img=new Image();img.onload=()=>{const settings=page.settings||{},assetScale=(Number(settings.scale)||100)/100,maxW=w*.72,maxH=h*.72,ratio=Math.min(maxW/img.width,maxH/img.height)*assetScale,dw=img.width*ratio,dh=img.height*ratio,x=(w-dw)/2+(Number(settings.x)||0)*scale/5,y=32*scale+(h-42*scale-dh)/2+(Number(settings.y)||0)*scale/5;ctx.drawImage(img,x,y,dw,dh)};img.src=data}
function drawFallback(canvas,page){const ctx=canvas.getContext("2d");ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#64748b";ctx.textAlign="center";ctx.font=`700 ${Math.max(14,canvas.width/13)}px Arial`;ctx.fillText(page.title||"Strona",canvas.width/2,canvas.height/2)}
function render(canvas,page,width,height,label){if(!canvas)return;canvas.width=width;canvas.height=height;canvas.setAttribute("aria-label",`${label}: ${page.title||"strona"}`);try{if(page.module==="maze-studio")drawMaze(canvas,page);else if(page.module==="coloring-studio")drawColoring(canvas,page);else if(page.module==="tracing-studio")drawTracingPage(canvas,page);else if(page.module==="logic-studio")drawLogicPage(canvas,page);else drawFallback(canvas,page)}catch(error){console.error("Page render failed",error,page);drawFallback(canvas,page)}}
export function renderPageThumbnail(canvas,page){render(canvas,page,180,233,"Miniatura")}
export function renderPagePreview(canvas,page){render(canvas,page,900,1165,"Podgląd strony")}