"use strict";
(()=>{
  const module=document.body.dataset.module,$=id=>document.getElementById(id),definition=FenixEndingRenderers.DEFINITIONS[module],canvas=$("page"),ctx=canvas.getContext("2d");if(!definition)return;
  const STRUCTURAL=new Set(["intro-studio","blank-page","certificate-studio","congratulations-studio","qr-studio","solutions-studio"]),activityCount=()=>FenixCore.getCart().filter(p=>!STRUCTURAL.has(FenixPageSchema.moduleOf(p))).length,existing=()=>FenixCore.getCart().find(p=>FenixPageSchema.moduleOf(p)===module)||null;
  const image=id=>new Promise(resolve=>{const a=FenixCore.getAsset(id);if(!a?.dataUrl)return resolve(null);const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>resolve(null);im.src=a.dataUrl});
  function settings(){const d=definition.defaults,s={...d};document.querySelectorAll('[data-setting]').forEach(el=>{const k=el.dataset.setting;if(el.type==='checkbox')s[k]=el.checked;else if(el.type==='number')s[k]=Number(el.value);else s[k]=el.value});if(s.countMode==='auto'&&'activityCount'in s)s.activityCount=activityCount();if(s.bookTitleMode==='auto'&&'bookTitle'in s)s.bookTitle=FenixCore.getActiveProject().name;return s}
  function fill(){const page=existing(),s=page?FenixEndingRenderers.fromPage(page,module):{...definition.defaults};if(s.countMode==='auto'&&'activityCount'in s)s.activityCount=activityCount();if(s.bookTitleMode==='auto'&&'bookTitle'in s)s.bookTitle=FenixCore.getActiveProject().name;document.querySelectorAll('[data-setting]').forEach(el=>{const k=el.dataset.setting;if(!(k in s))return;if(el.type==='checkbox')el.checked=Boolean(s[k]);else el.value=s[k]??''});$("save").textContent=page?'Zapisz zmiany':'Dodaj stronę do projektu';$("state").textContent=page?'✓ Strona jest już w projekcie':'Strona nie została jeszcze dodana'}
  async function render(){const s=settings(),page=FenixEndingRenderers.page(module,s,existing());let qr=null,creator=null;if(module==='qr-studio'&&s.qrAssetRef)qr=await image(s.qrAssetRef);if(module==='certificate-studio'&&s.creatorMarkAssetRef)creator=await image(s.creatorMarkAssetRef);const out=FenixEndingRenderers.render(page,{width:2550,height:3300,qrAssetImage:qr,creatorMarkImage:creator});canvas.width=out.width;canvas.height=out.height;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(out,0,0);$("status").textContent='Podgląd aktualny'}
  function assetOptions(){const assets=FenixCore.listAssets(),options='<option value="">— wybierz asset projektu —</option>'+assets.map(a=>`<option value="${a.id}">${a.name}</option>`).join('');document.querySelectorAll('select[data-asset]').forEach(el=>{const v=el.value;el.innerHTML=options;if(v)el.value=v})}
  async function save(){const s=settings(),old=existing(),page=FenixEndingRenderers.page(module,s,old);if(old)FenixCore.updatePage(old.id,page);else FenixCore.addPage(page);fill();await render();$("state").textContent='✓ Zapisano w aktywnym projekcie'}
  document.querySelectorAll('[data-setting]').forEach(el=>el.addEventListener(el.type==='text'||el.tagName==='TEXTAREA'||el.type==='number'?'input':'change',()=>{clearTimeout(window.__endingTimer);window.__endingTimer=setTimeout(render,100)}));$("save").onclick=save;$("png").onclick=()=>FenixCore.downloadCanvas(canvas,`${definition.file}-300dpi.png`);window.addEventListener('fenix-assets-change',()=>{assetOptions();render()});assetOptions();fill();render();
})();