"use strict";
(()=>{
 const $=id=>document.getElementById(id),canvas=$("page"),ctx=canvas.getContext("2d"),LETTERS="ABCDEFGHJKLMNPQRSTUVWXYZ".split(""),WORDS=["CAT","DOG","SUN","STAR","MOON","TREE","FISH","BIRD"];
 const state={pages:[],index:0,view:"task"};const editId=new URLSearchParams(location.search).get("id")||null;
 const val=(id,f="")=>$(id)?.value??f, num=(id,f)=>Number(val(id,f))||f;
 function seeded(seed){let h=2166136261;for(const ch of String(seed||"fenix")){h=Math.imul(h^ch.charCodeAt(0),16777619)}return()=>{h+=0x6D2B79F5;let t=h;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
 const pick=(a,r)=>a[Math.floor(r()*a.length)],shuffle=(a,r)=>{const o=a.slice();for(let i=o.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[o[i],o[j]]=[o[j],o[i]]}return o};
 function instructions(type){return {"letter-day":"Practice the letter.",trace:"Trace the letters.",find:"Find and circle the letter.","match-case":"Match uppercase and lowercase letters.",missing:"Write the missing letters.",words:"Copy the words."}[type]||"Practice the letter."}
 function opts(){const type=val("type","letter-day");return{type,difficulty:val("difficulty","medium"),age:val("age","5-7"),language:val("language","en"),count:Math.max(1,Math.min(20,num("count",1))),seed:val("seed","fenix-abc"),extra:(val("extra","A")||"A").slice(0,1).toUpperCase(),title:val("title","Alphabet Practice"),instructions:val("instructions","")||instructions(type)}}
 function make(){const c=document.createElement("canvas");c.width=850;c.height=1100;return c}
 function base(c,o){c.fillStyle="#fff";c.fillRect(0,0,850,1100);c.strokeStyle="#111827";c.lineWidth=3;c.strokeRect(36,36,778,1028);c.fillStyle="#111827";c.textAlign="center";c.font="700 38px Arial";c.fillText(String(o.title||"Alphabet Practice").slice(0,60),425,92);c.font="20px Arial";c.fillText(String(o.instructions||"Practice the letter.").slice(0,95),425,132)}
 function solutionBase(c,title){c.fillStyle="#fff";c.fillRect(0,0,850,1100);c.strokeStyle="#111827";c.lineWidth=3;c.strokeRect(36,36,778,1028);c.fillStyle="#111827";c.textAlign="center";c.font="700 34px Arial";c.fillText(`Solution — ${String(title||"Alphabet Practice").slice(0,50)}`,425,90)}
 function circle(c,x,y,r=25){c.save();c.strokeStyle="#111";c.lineWidth=4;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.stroke();c.restore()}
 function connect(c,x1,y1,x2,y2){c.save();c.strokeStyle="#111";c.lineWidth=3;c.beginPath();c.moveTo(x1,y1);c.lineTo(x2,y2);c.stroke();c.restore()}
 function renderOne(o,seed,pageNo){const page=make(),solution=make(),p=page.getContext("2d"),s=solution.getContext("2d"),r=seeded(seed),letter=o.extra||"A",lower=letter.toLowerCase();base(p,o);solutionBase(s,o.title);p.fillStyle=s.fillStyle="#111";p.strokeStyle=s.strokeStyle="#111";let hasSolution=false;
  if(o.type==="find"){hasSolution=true;p.font=s.font="38px Arial";p.textAlign=s.textAlign="center";for(let y=0;y<8;y++)for(let x=0;x<9;x++){const px=110+x*78,py=220+y*90,v=r()<.22?letter:pick(LETTERS,r);p.fillText(v,px,py);s.fillText(v,px,py);if(v===letter)circle(s,px,py-13,26)}}
  else if(o.type==="match-case"){hasSolution=true;const left=shuffle(LETTERS,r).slice(0,6),right=shuffle(left.map(x=>x.toLowerCase()),r);p.font=s.font="42px Arial";p.textAlign=s.textAlign="center";for(let i=0;i<6;i++){const y=250+i*115;p.fillText(left[i],180,y);p.fillText(right[i],650,y);s.fillText(left[i],180,y);s.fillText(right[i],650,y)}left.forEach((v,i)=>connect(s,210,235+i*115,620,235+right.indexOf(v.toLowerCase())*115))}
  else if(o.type==="missing"){hasSolution=true;p.font=s.font="38px Arial";p.textAlign=s.textAlign="left";for(let row=0;row<7;row++){const start=Math.floor(r()*20),letters=[0,1,2,3,4].map(i=>String.fromCharCode(65+start+i));p.fillText(`${letters[0]}   ${letters[1]}   ____   ${letters[3]}   ${letters[4]}`,160,240+row*105);s.fillText(letters.join("   "),160,240+row*105)}}
  else if(o.type==="trace"){p.textAlign="left";p.font="90px Arial";p.setLineDash([8,8]);for(let y=270;y<900;y+=140)p.strokeText(`${letter} ${letter} ${letter}    ${lower} ${lower} ${lower}`,90,y);p.setLineDash([])}
  else if(o.type==="words"){p.textAlign="left";p.font="42px Arial";WORDS.filter(w=>w.includes(letter)).concat(WORDS).slice(0,6).forEach((word,i)=>p.fillText(`${word}   __________________`,110,250+i*115))}
  else{p.textAlign="center";p.font="700 300px Arial";p.fillText(letter,425,520);p.font="58px Arial";p.fillText(`${letter} ${letter} ${letter}    ${lower} ${lower} ${lower}`,425,720)}
  return{page,solution:hasSolution?solution:null,hasSolution,seed,o};}
 function build(){const o=opts();state.pages=[];for(let i=0;i<o.count;i++)state.pages.push(renderOne(o,`${o.seed}-${i+1}`,i));state.index=0;show();$("status").textContent=`Wygenerowano ${state.pages.length} stron.`}
 function show(){const item=state.pages[state.index];if(!item)return;const src=state.view==="solution"&&item.solution?item.solution:item.page;canvas.width=850;canvas.height=1100;ctx.clearRect(0,0,850,1100);ctx.drawImage(src,0,0);$("pageCounter").textContent=`${state.index+1} / ${state.pages.length}`;$("prev").disabled=state.index===0;$("next").disabled=state.index===state.pages.length-1;$("solutionTab").disabled=!item.hasSolution}
 function payload(item,index){return FenixPageSchema.normalize({module:"alphabet-studio",title:item.o.title,seed:item.seed,recipe:{module:"alphabet-studio",seed:item.seed,title:item.o.title,settings:{...item.o,pageIndex:index},meta:{createdWith:"FPM",moduleVersion:3}},preview:{imageData:item.page.toDataURL("image/png")},solution:{available:item.hasSolution,imageData:item.solution?item.solution.toDataURL("image/png"):null},source:{app:"fenix-portable-mobile",version:"3.5",format:"native"}})}
 function save(){if(!state.pages.length)build();if(editId){const item=state.pages[0];FenixCore.updatePage(editId,payload(item,0));$("status").textContent="Zapisano zmiany tej strony.";$("cart").textContent="✓ Zapisano — edytuj dalej";return}state.pages.forEach((item,i)=>FenixCore.addPage(payload(item,i)));$("status").textContent=`Dodano ${state.pages.length} stron do projektu.`}
 function loadEdit(){if(!editId)return;const raw=FenixCore.getCart().find(p=>String(p.id)===String(editId));if(!raw||FenixPageSchema.moduleOf(raw)!=="alphabet-studio")return;const p=FenixPageSchema.normalize(raw),s=p.recipe?.settings||{};["type","difficulty","age","language","seed","extra","title","instructions"].forEach(id=>{if(s[id]!=null&&$(id))$(id).value=s[id]});$("seed").value=String(p.recipe?.seed||p.seed||s.seed||"fenix-abc").replace(/-\d+$/,'');$("count").value=1;$("cart").textContent="Zapisz zmiany";$("editBadge").classList.add("on")}
 $("type").onchange=()=>{if(!editId||!val("instructions",""))$("instructions").value=instructions(val("type"));build()};["difficulty","age","language"].forEach(id=>$(id).onchange=build);["count","seed","extra","title","instructions"].forEach(id=>$(id).oninput=()=>{clearTimeout(window.__abcTimer);window.__abcTimer=setTimeout(build,120)});$("preset").onchange=()=>{const p={preschool:["3-5","easy"],early:["5-7","medium"],advanced:["7-9","hard"]}[val("preset")];if(p){$("age").value=p[0];$("difficulty").value=p[1];build()}};$("randomSeed").onclick=()=>{$("seed").value=`fenix-abc-${Date.now().toString(36)}`;build()};$("prev").onclick=()=>{if(state.index>0){state.index--;show()}};$("next").onclick=()=>{if(state.index<state.pages.length-1){state.index++;show()}};$("taskTab").onclick=()=>{state.view="task";$("taskTab").classList.add("active");$("solutionTab").classList.remove("active");show()};$("solutionTab").onclick=()=>{state.view="solution";$("solutionTab").classList.add("active");$("taskTab").classList.remove("active");show()};$("png").onclick=()=>{const item=state.pages[state.index];if(!item)return;const src=state.view==="solution"&&item.solution?item.solution:item.page,a=document.createElement("a");a.href=src.toDataURL("image/png");a.download=`alphabet-${item.seed}.png`;a.click()};$("cart").onclick=save;
 const project=FenixCore.getActiveProject();$("projectInfo").textContent=`Aktywny projekt: ${project.name} · ${project.format}`;loadEdit();if(!val("instructions",""))$("instructions").value=instructions(val("type"));build();
})();