"use strict";
(()=>{
const $=s=>document.querySelector(s),canvas=$("#page"),ctx=canvas.getContext("2d"),ASSETS=[...FenixCompletePicture.ASSETS],HELP={"half-vertical":"Jedna pionowa połowa rysunku pozostaje widoczna. Dziecko dorysowuje drugą stronę, korzystając z osi symetrii.","half-horizontal":"Widoczna jest górna połowa rysunku. Dolną część należy odtworzyć.","shadow-trace":"Cały obrazek jest pokazany jako delikatny ślad. Dziecko prowadzi ołówek po konturze.","grid-copy":"Rysunek znajduje się w lewej siatce, a dziecko kopiuje go pole po polu do pustej siatki po prawej.","missing-part":"Z kompletnego rysunku usuwany jest fragment do dorysowania.","mirror-pair":"Po jednej stronie osi znajduje się obrazek. Po drugiej należy narysować jego lustrzane odbicie."},DEFAULTS={"half-vertical":"Draw the missing half of the picture.","half-horizontal":"Draw the missing bottom half of the picture.","shadow-trace":"Trace the picture by following the shadow.","grid-copy":"Copy the picture into the empty grid.","missing-part":"Draw the missing part of the picture.","mirror-pair":"Draw the mirror image on the other side."};
let pages=[],index=0,showSolution=false,timer=null,editId=new URLSearchParams(location.search).get("id")||null;
function status(t){$("#status").textContent=t}function loadImage(src){return new Promise(resolve=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>resolve(null);im.src=src})}
function opts(){return{type:$("#type").value,assetSource:$("#assetSource").value,asset:$("#asset").value,projectAssetRef:$("#projectAsset").value||null,difficulty:$("#difficulty").value,age:$("#age").value,scale:(+$("#scale").value||94)/100,lineWidth:+$("#lineWidth").value||4,shadow:(+$("#shadowStrength").value||28)/100,shadowScale:1.4,shadowAssetScale:1,guide:$("#showGuide").checked,dots:$("#showDots").checked,grid:$("#showGrid").checked,missingGuide:"faint",missingGuideOpacity:.20,missingGuideLineWidth:1.5,missingPartSize:$("#difficulty").value==="easy"?.42:$("#difficulty").value==="hard"?.25:.34,missingPartPosition:"random",referenceSize:100,title:$("#title").value.trim()||"Complete the Picture",instruction:$("#instruction").value.trim()||DEFAULTS[$("#type").value],count:Math.max(1,Math.min(20,+$("#count").value||1)),seed:$("#seed").value.trim()||"fenix-ctp",seriesMode:$("#seriesMode").value}}
async function imageFor(o){if(o.assetSource==="built-in")return null;const a=FenixCore.getAsset(o.projectAssetRef);return a?.dataUrl?loadImage(a.dataUrl):null}
function coreOptions(o){return{...o,assetSource:o.assetSource==="built-in"?"built-in":"upload"}}
async function build(){const o=opts();if(o.assetSource!=="built-in"&&!o.projectAssetRef){status("Wybierz asset projektu.");return}const image=await imageFor(o),count=editId?1:o.count;pages=[];for(let i=0;i<count;i++){const asset=o.assetSource==="built-in"&&o.seriesMode==="mixed"?ASSETS[i%ASSETS.length]:o.asset;pages.push({o:{...o,asset},seed:editId?o.seed:`${o.seed}-${i+1}`,num:i,image})}index=0;showSolution=false;show();status(editId?"Wczytano stronę do edycji.":`Wygenerowano ${pages.length} stron.`)}
function render(p,solution){const out=FenixCompletePicture.render(coreOptions(p.o),p.seed,p.num,{solution,scale:1,customImage:p.image});canvas.width=out.width;canvas.height=out.height;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(out,0,0)}
function show(){if(!pages.length)return;render(pages[index],showSolution);$("#pageCounter").textContent=`${index+1} / ${pages.length}`;$("#prev").disabled=index===0;$("#next").disabled=index===pages.length-1;$("#solution").textContent=showSolution?"Pokaż ćwiczenie":"Pokaż rozwiązanie"}
function live(){clearTimeout(timer);timer=setTimeout(build,120)}
function refreshProjectAssets(){const assets=FenixCore.listAssets();$("#projectAsset").innerHTML='<option value="">— wybierz —</option>'+assets.map(a=>`<option value="${a.id}">${a.name}</option>`).join("")}
function sourceUi(){const s=$("#assetSource").value;$("#builtInWrap").hidden=s!=="built-in";$("#projectAssetWrap").hidden=s==="built-in";$("#uploadWrap").hidden=s!=="upload";$("#seriesMode").disabled=s!=="built-in";live()}
function typeUi(updateInstruction=true){const type=$("#type").value;$("#typeHelp").textContent=HELP[type];$("#shadowStrengthField").hidden=type!=="shadow-trace";if(updateInstruction)$("#instruction").value=DEFAULTS[type];live()}
async function importFile(file){if(!file)return;try{const dataUrl=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(r.error);r.readAsDataURL(file)}),saved=FenixCore.putAsset({name:file.name.replace(/\.[^.]+$/,"")||"Asset",filename:file.name,mime:file.type||"image/png",dataUrl,source:"complete-picture-upload",sizeBytes:file.size,tags:["content"]});refreshProjectAssets();$("#projectAsset").value=saved.id;$("#assetSource").value="project";$("#uploadStatus").textContent=`Wczytano do Assetów projektu: ${file.name}`;sourceUi();build()}catch(e){status("Nie udało się wczytać assetu.")}}
function pageRecord(p){const o=p.o;render(p,false);const imageData=canvas.toDataURL("image/png");render(p,true);const solutionImageData=canvas.toDataURL("image/png"),recipe={module:"complete-picture",seed:p.seed,title:o.title,settings:{...o,seed:p.seed,assetSource:o.assetSource==="built-in"?"built-in":"project"},content:{assetRef:o.assetSource==="built-in"?null:o.projectAssetRef},meta:{createdWith:"FPM",moduleVersion:2,sharedRenderer:true}};return FenixPageSchema.normalize({module:"complete-picture",title:o.title,seed:p.seed,recipe,imageData,solutionImageData,solution:{available:true,imageData:solutionImageData},preview:{imageData},source:{app:"fenix-portable-mobile",version:"3.9",format:"native"}})}
function save(){if(!pages.length)return status("Najpierw wygeneruj stronę.");if(editId){FenixCore.updatePage(editId,pageRecord(pages[0]));status("✓ Zapisano zmiany tej strony.");return}for(const p of pages)FenixCore.addPage(pageRecord(p));status(`✓ Dodano ${pages.length} stron Complete the Picture do projektu.`)}
function loadEdit(){if(!editId)return;const raw=FenixCore.getCart().find(p=>String(p.id)===String(editId));if(!raw)return;const p=FenixPageSchema.normalize(raw);if(FenixPageSchema.moduleOf(p)!=="complete-picture")return;const s=p.recipe?.settings||{},c=p.recipe?.content||{};$("#editBadge").classList.add("on");$("#cart").textContent="Zapisz zmiany";$("#count").value=1;$("#count").disabled=true;const set=(id,v)=>{if(v!=null&&$("#"+id))$("#"+id).value=v},chk=(id,v)=>{if($("#"+id))$("#"+id).checked=Boolean(v)};set("type",s.type||"half-vertical");set("assetSource",s.assetSource==="built-in"?"built-in":"project");set("asset",s.asset||"butterfly");set("projectAsset",s.projectAssetRef||c.assetRef||"");set("difficulty",s.difficulty||"medium");set("age",s.age||"5–7");set("scale",Math.round((s.scale||.94)*100));set("lineWidth",s.lineWidth||4);set("shadowStrength",Math.round((s.shadow||.28)*100));chk("showGuide",s.guide!==false);chk("showDots",s.dots);chk("showGrid",s.grid);set("title",p.title||s.title||"Complete the Picture");set("instruction",s.instruction||DEFAULTS[s.type||"half-vertical"]);set("seed",p.recipe?.seed||p.seed||"fenix-ctp-001");set("seriesMode",s.seriesMode||"selected");sourceUi();typeUi(false);build()}
$("#generate").onclick=build;$("#variant").onclick=()=>{$("#seed").value=`fenix-ctp-${Math.random().toString(36).slice(2,8)}`;build()};$("#prev").onclick=()=>{if(index>0){index--;show()}};$("#next").onclick=()=>{if(index<pages.length-1){index++;show()}};$("#solution").onclick=()=>{showSolution=!showSolution;show()};$("#png").onclick=()=>{if(!pages.length)return;render(pages[index],showSolution);FenixCore.downloadCanvas(canvas,`complete-picture-${Date.now()}.png`)};$("#cart").onclick=save;$("#type").onchange=()=>typeUi(true);$("#assetSource").onchange=sourceUi;$("#assetFile").onchange=e=>importFile(e.target.files?.[0]);["asset","projectAsset","difficulty","age","scale","lineWidth","shadowStrength","showGuide","showDots","showGrid","title","instruction","count","seed","seriesMode"].forEach(id=>$("#"+id)?.addEventListener(["title","instruction","seed"].includes(id)?"input":"change",live));
const project=FenixCore.getActiveProject();$("#projectInfo").textContent=`Aktywny projekt: ${project.name} · ${project.pages.length} stron`;refreshProjectAssets();sourceUi();typeUi(false);loadEdit();if(!editId)build();
})();