(()=>{
  const body=document.body;if(!body)return;
  const shellScript=[...document.scripts].find(s=>/fpm-shell\.js(?:\?|$)/.test(s.src)),root=shellScript?new URL('./',shellScript.src):new URL('./',location.href),url=path=>new URL(path,root).href;
  const pageName=location.pathname.split('/').pop(),isStudioPage=pageName!==''&&pageName!=='index.html';
  const structuralRoutes={'intro-studio':'modules/intro-studio/index.html','congratulations-studio':'modules/congratulations-studio/index.html','qr-studio':'modules/qr-studio/index.html','certificate-studio':'modules/certificate-studio/index.html'};
  function moduleOf(page){try{return window.FenixPageSchema?.moduleOf?page&&FenixPageSchema.moduleOf(page):(page?.module||page?.recipe?.module||'unknown')}catch{return page?.module||page?.recipe?.module||'unknown'}}
  const routeFor=page=>{const mod=moduleOf(page),id=encodeURIComponent(page.id),map={'word-search-studio':'word-search.html','coloring-studio':'coloring.html','complete-picture':'complete-picture.html','tracing-studio':'tracing.html','matching-studio':'matching.html','alphabet-studio':'alphabet.html','dot-to-dot-studio':'dot-to-dot.html','hidden-objects-studio':'hidden-objects.html','logic-studio':'logic.html'};if(mod==='maze-studio')return url('index.html?id='+id+'#maze');if(map[mod])return url(map[mod]+'?id='+id);if(structuralRoutes[mod])return url(structuralRoutes[mod]);return''};
  if(window.FenixCore){const originalOpen=window.openFpmPage;window.openFpmPage=id=>{const page=FenixCore.getCart().find(item=>String(item.id)===String(id));if(!page)return;const mod=moduleOf(page);if(mod==='maze-studio'&&typeof originalOpen==='function'&&pageName==='index.html')return originalOpen(id);const route=routeFor(page);if(route)location.href=route;else alert('Ta strona jest zapisana poprawnie, ale jej Studio nie zostało jeszcze przeniesione do FPM.')};
    const enhance=()=>{const list=document.getElementById('pageList');if(!list)return;const pages=FenixCore.getCart();[...list.querySelectorAll('.page')].forEach((card,index)=>{const page=pages[index],route=page&&routeFor(page);if(!route)return;if(!card.querySelector('.fpm-page-edit')){const a=document.createElement('a');a.className='fpm-page-edit';a.textContent='Edytuj →';a.href=route;a.style.cssText='display:inline-flex;margin-top:8px;font-weight:900;color:#e45520;text-decoration:none';a.onclick=e=>e.stopPropagation();card.appendChild(a)}})};enhance();const list=document.getElementById('pageList');if(list)new MutationObserver(enhance).observe(list,{childList:true});window.addEventListener('fenix-state-change',()=>setTimeout(enhance,0))}
  if(pageName==='index.html'||pageName===''){
    const nav=document.querySelector('.nav');if(nav&&!nav.querySelector('[data-fenix-book-builder]')){const b=document.createElement('button');b.dataset.fenixBookBuilder='1';b.textContent='Book Builder';b.onclick=()=>location.href=url('modules/book-builder/index.html');nav.appendChild(b)}
    const tiles=document.querySelector('#home .tiles');if(tiles&&!tiles.querySelector('[data-fenix-book-builder]')){const b=document.createElement('button');b.dataset.fenixBookBuilder='1';b.innerHTML='<b>▤ · Book Builder</b><small>Finalny skład · Solutions · PDF 300 DPI</small>';b.onclick=()=>location.href=url('modules/book-builder/index.html');tiles.prepend(b)}
  }
  const bar=document.createElement('section');bar.className='fpm-active-bar';bar.innerHTML=`<button class="fpm-bar-handle" type="button" aria-expanded="false"><span></span><small>MODUŁY</small></button><div class="fpm-bar-content" aria-hidden="true"><div class="fpm-bar-utility"><button data-shell-target="home"><span>⌂</span><small>Start</small></button><button data-shell-target="pages"><span>▣</span><small>Projekt</small></button><button data-shell-target="assets"><span>◆</span><small>Assety</small></button></div><div class="fpm-bar-label">WYBIERZ MODUŁ</div><div class="fpm-module-strip"><button data-shell-target="intro"><b>INTRO</b><span>Intro Studio</span></button><button data-shell-target="maze"><b>MAZE</b><span>Maze Studio</span></button><button data-shell-target="word-search"><b>WS</b><span>Word Search</span></button><button data-shell-target="coloring"><b>COL</b><span>Coloring</span></button><button data-shell-target="tracing"><b>TR</b><span>Tracing</span></button><button data-shell-target="matching"><b>MATCH</b><span>Matching</span></button><button data-shell-target="alphabet"><b>ABC</b><span>Alphabet</span></button><button data-shell-target="dot"><b>DOT</b><span>Dot to Dot</span></button><button data-shell-target="hidden"><b>HO</b><span>Hidden Objects</span></button><button data-shell-target="logic"><b>LOG</b><span>Logic</span></button><button data-shell-target="congratulations"><b>CONG</b><span>Congratulations</span></button><button data-shell-target="qr"><b>QR</b><span>QR Studio</span></button><button data-shell-target="certificate"><b>CERT</b><span>Certificate</span></button><button data-shell-target="book-builder"><b>▤</b><span>Book Builder</span></button></div></div>`;body.appendChild(bar);
  const handle=bar.querySelector('.fpm-bar-handle'),content=bar.querySelector('.fpm-bar-content');let open=false,timer=null;function setOpen(v){open=!!v;clearTimeout(timer);bar.classList.toggle('open',open);handle.setAttribute('aria-expanded',String(open));content.setAttribute('aria-hidden',String(!open))}function close(){timer=setTimeout(()=>setOpen(false),180)}
  function go(target){close();const direct={intro:'modules/intro-studio/index.html','word-search':'word-search.html',coloring:'coloring.html',tracing:'tracing.html',matching:'matching.html',alphabet:'alphabet.html',dot:'dot-to-dot.html',hidden:'hidden-objects.html',logic:'logic.html',congratulations:'modules/congratulations-studio/index.html',qr:'modules/qr-studio/index.html',certificate:'modules/certificate-studio/index.html','book-builder':'modules/book-builder/index.html'};if(direct[target]){setTimeout(()=>location.href=url(direct[target]),120);return}if(isStudioPage){setTimeout(()=>location.href=url(target==='home'?'index.html':`index.html#${target}`),120);return}const legacy=document.querySelector(`[data-view="${target}"]`)||document.querySelector(`[data-go="${target}"]`);if(legacy)legacy.click()}
  handle.onclick=()=>setOpen(!open);bar.querySelectorAll('[data-shell-target]').forEach(b=>b.onclick=()=>go(b.dataset.shellTarget));
  if(!window.FenixSync&&!document.querySelector('script[data-fpm-sync-core]')){const core=document.createElement('script');core.src=url('core/sync-core.js?v=2');core.dataset.fpmSyncCore='1';core.onload=()=>{if(document.getElementById('fenixSyncButton'))return;const ui=document.createElement('script');ui.src=url('core/sync-ui.js?v=2');ui.dataset.fpmSyncUi='1';document.body.appendChild(ui)};document.body.appendChild(core)}
})();