"use strict";
(()=>{
  const $=id=>document.getElementById(id),canvas=$("page");
  const state={projectAssets:[],selected:null,rendered:null};let timer=null;
  const editId=new URLSearchParams(location.search).get("id")||null;
  const val=(id,f="")=>$(id)?.value??f,checked=id=>Boolean($(id)?.checked),num=(id,f)=>Number(val(id,f))||f;
  const opts=()=>({scaleX:num("scaleX",80),scaleY:num("scaleY",80),assetX:num("assetX",50),assetY:num("assetY",58),rotation:num("rotation",0),workMargin:num("workMargin",8),flipX:checked("flipX"),flipY:checked("flipY"),showFrame:checked("showFrame"),treatment:val("treatment","dots"),threshold:num("threshold",180),edgeStrength:num("edgeStrength",35),dotSize:num("dotSize",8),dotSpacing:num("dotSpacing",22),dotOpacity:num("dotOpacity",70),dashLength:num("dashLength",24),dashSpacing:num("dashSpacing",18),dashWidth:num("dashWidth",6),dashOpacity:num("dashOpacity",70),exerciseMode:val("exerciseMode","single"),repeatCount:num("repeatCount",4),progressEndOpacity:num("progressEndOpacity",15),brightness:num("brightness",105),contrast:num("contrast",125),opacity:num("opacity",42),invert:checked("invert"),smooth:checked("smooth"),title:val("title","Trace the Picture!"),instructions:val("instructions","Trace the picture carefully."),titleSize:num("titleSize",112),titleY:num("titleY",230),instructionSize:num("instructionSize",46)});
  const safe=s=>String(s||"").replace(/[&<>"']/g,"");
  function status(t,e=false){$("status").textContent=t;$("status").dataset.type=e?"error":"ok"}
  function currentAsset(){return state.projectAssets.find(a=>String(a.id)===String(state.selected))||null}
  function renderProjectAssets(){state.projectAssets=FenixCore.listAssets();if(state.selected&&!state.projectAssets.some(a=>String(a.id)===String(state.selected)))state.selected=null;if(!state.selected&&state.projectAssets.length)state.selected=state.projectAssets[0].id;$("assetEmpty").hidden=state.projectAssets.length>0;const g=$("assetGrid");g.innerHTML="";for(const a of state.projectAssets){const b=document.createElement("button");b.type="button";b.className=`asset-card${String(state.selected)===String(a.id)?" selected":""}`;b.innerHTML=`<img src="${a.dataUrl}" alt=""><strong>${safe(a.name||"Asset")}</strong>`;b.onclick=()=>{state.selected=a.id;renderProjectAssets();render()};g.appendChild(b)}$("selectedAssetName").textContent=currentAsset()?.name||"Brak assetu"}
  function drawPlaceholder(message){canvas.width=850;canvas.height=1100;const c=canvas.getContext("2d");c.fillStyle="#fff";c.fillRect(0,0,850,1100);c.strokeStyle="#cbd5df";c.lineWidth=3;c.setLineDash([10,10]);c.strokeRect(34,34,782,1032);c.setLineDash([]);c.fillStyle="#647383";c.textAlign="center";c.font="700 34px Arial";c.fillText("Tracing Studio",425,470);c.font="22px Arial";c.fillText(message,425,520)}
  async function render(){clearTimeout(timer);try{const a=currentAsset();if(!a){state.rendered=null;drawPlaceholder("Dodaj lub wybierz asset");return status("Wybierz asset projektu.",true)}state.rendered=await FenixTracingCore.render(a,opts());canvas.width=state.rendered.width;canvas.height=state.rendered.height;const c=canvas.getContext("2d");c.clearRect(0,0,canvas.width,canvas.height);c.drawImage(state.rendered,0,0);$("selectedAssetName").textContent=a.name;status(editId?"Podgląd strony w trybie edycji.":"Podgląd gotowy.")}catch(e){console.error(e);state.rendered=null;drawPlaceholder("Błąd renderowania podglądu");status(e.message||"Błąd renderowania",true)}}
  const schedule=()=>{clearTimeout(timer);timer=setTimeout(render,120)};
  async function importFiles(files){for(const file of files){const dataUrl=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result));r.onerror=()=>rej(new Error("Nie udało się odczytać pliku."));r.readAsDataURL(file)});const img=await FenixTracingCore.loadImage(dataUrl);const a=FenixCore.putAsset({name:file.name.replace(/\.[^.]+$/,"")||file.name,filename:file.name,mime:file.type||"image/png",dataUrl,source:"tracing-studio",width:img.naturalWidth||img.width,height:img.naturalHeight||img.height,sizeBytes:file.size,tags:["content"]});state.selected=a.id}renderProjectAssets();render()}
  function reset(){const d={scaleX:80,scaleY:80,assetX:50,assetY:58,rotation:0,workMargin:8,threshold:180,edgeStrength:35,dotSize:8,dotSpacing:22,dotOpacity:70,dashLength:24,dashSpacing:18,dashWidth:6,dashOpacity:70,repeatCount:4,progressEndOpacity:15,brightness:105,contrast:125,opacity:42,titleSize:112,titleY:230,instructionSize:46};for(const[k,v]of Object.entries(d))if($(k))$(k).value=v;$("flipX").checked=$("flipY").checked=$("showFrame").checked=$("invert").checked=false;$("smooth").checked=true;$("treatment").value="dots";$("exerciseMode").value="single";render()}
  function record(){const a=currentAsset(),o=opts(),imageData=state.rendered?state.rendered.toDataURL("image/png"):null;return FenixPageSchema.normalize({module:"tracing-studio",title:o.title,recipe:{module:"tracing-studio",title:o.title,settings:o,content:{assetRef:a?.id||null},meta:{createdWith:"FPM",moduleVersion:5}},content:{assetRef:a?.id||null},preview:{imageData},imageData,solution:{available:false,imageData:null},source:{app:"fenix-portable-mobile",version:"3.3",format:"native"}})}
  function save(){const a=currentAsset();if(!a)return status("Najpierw wybierz asset.",true);const page=record();if(editId){FenixCore.updatePage(editId,page);status(`Zapisano zmiany strony z assetem „${a.name}”.`)}else{FenixCore.addPage(page);status(`Dodano stronę z assetem „${a.name}” do projektu.`)}}
  function download(){if(!state.rendered)return;const a=document.createElement("a");a.href=state.rendered.toDataURL("image/png");a.download=`tracing-${Date.now()}.png`;a.click()}
  function loadEdit(){if(!editId)return;const raw=FenixCore.getCart().find(p=>String(p.id)===String(editId));if(!raw||FenixPageSchema.moduleOf(raw)!=="tracing-studio")return;const p=FenixPageSchema.normalize(raw),s=p.recipe?.settings||{},ref=p.recipe?.content?.assetRef||p.content?.assetRef||null;state.selected=ref;for(const id of ["scaleX","scaleY","assetX","assetY","rotation","workMargin","threshold","edgeStrength","dotSize","dotSpacing","dotOpacity","dashLength","dashSpacing","dashWidth","dashOpacity","repeatCount","progressEndOpacity","brightness","contrast","opacity","title","instructions","titleSize","titleY","instructionSize"]){if(s[id]!=null&&$(id))$(id).value=s[id]}for(const id of ["flipX","flipY","showFrame","invert","smooth"]){if(s[id]!=null&&$(id))$(id).checked=Boolean(s[id])}for(const id of ["treatment","exerciseMode"]){if(s[id]!=null&&$(id))$(id).value=s[id]}$("cart").textContent="Zapisz zmiany";$("editBadge").classList.add("on")}
  $("importAsset").onclick=()=>$("assetFile").click();$("assetFile").onchange=async()=>{if($("assetFile").files?.length)await importFiles([...$("assetFile").files]);$("assetFile").value=""};$("generate").onclick=render;$("reset").onclick=reset;$("cart").onclick=save;$("png").onclick=download;
  ["scaleX","scaleY","assetX","assetY","rotation","workMargin","threshold","edgeStrength","dotSize","dotSpacing","dotOpacity","dashLength","dashSpacing","dashWidth","dashOpacity","repeatCount","progressEndOpacity","brightness","contrast","opacity","title","instructions","titleSize","titleY","instructionSize"].forEach(id=>$(id)?.addEventListener("input",schedule));["flipX","flipY","showFrame","treatment","exerciseMode","invert","smooth"].forEach(id=>$(id)?.addEventListener("change",render));window.addEventListener("fenix-state-change",e=>{if(e.detail?.assets||e.detail?.activeProject||e.detail?.projects){renderProjectAssets();render()}});
  const p=FenixCore.getActiveProject();$("projectInfo").textContent=`Aktywny projekt: ${p.name} · ${p.format} · ${p.bleed==="bleed"?"ze spadami":"bez spadów"}`;loadEdit();renderProjectAssets();render();
})();