"use strict";
(()=>{
const $=s=>document.querySelector(s),list=$("#pageList"),empty=$("#empty"),previewGrid=$("#previewGrid"),progress=$("#progress"),validation=$("#validation");
let pages=[],dragIndex=null,renderToken=0;
const normalize=p=>FenixPageSchema.normalize(p),moduleOf=p=>FenixPageSchema.moduleOf(p),hasSolution=p=>FenixPageSchema.hasSolution?p&&FenixPageSchema.hasSolution(p):Boolean(p?.solution?.available),ending=new Set(["congratulations-studio","qr-studio","certificate-studio"]);
const NAMES={"intro-studio":"Intro","maze-studio":"Maze","word-search-studio":"Word Search","coloring-studio":"Coloring","complete-picture":"Complete the Picture","tracing-studio":"Tracing","matching-studio":"Matching","alphabet-studio":"Alphabet","dot-to-dot-studio":"Dot to Dot","hidden-objects-studio":"Hidden Objects","logic-studio":"Logic","congratulations-studio":"Congratulations","qr-studio":"QR","certificate-studio":"Certificate","blank-page":"Pusta strona"};
const loadImage=src=>new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(new Error("Nie udało się odczytać obrazu/assetu."));i.src=src});
function project(){return FenixCore.getActiveProject()}
function profile(){const f=$("#format").value;if(f==="6x9")return{width:1800,height:2700,dpi:300};if(f==="a4")return{width:2480,height:3508,dpi:300};return{width:2550,height:3300,dpi:300}}
function blankCanvas(quality="preview"){const p=quality==="print"?profile():{width:850,height:1100},c=document.createElement("canvas");c.width=p.width;c.height=p.height;const x=c.getContext("2d");x.fillStyle="#fff";x.fillRect(0,0,c.width,c.height);return c}
async function storedCanvas(data,quality="preview"){if(!data)return null;const img=await loadImage(data),p=quality==="print"?profile():{width:850,height:1100},c=document.createElement("canvas");c.width=p.width;c.height=p.height;const x=c.getContext("2d");x.fillStyle="#fff";x.fillRect(0,0,c.width,c.height);const s=Math.min(c.width/img.naturalWidth,c.height/img.naturalHeight),w=img.naturalWidth*s,h=img.naturalHeight*s;x.drawImage(img,(c.width-w)/2,(c.height-h)/2,w,h);return c}
async function renderCanvas(raw,solution=false,quality="preview"){
 const page=normalize(raw),mod=moduleOf(page),w=quality==="print"?2550:850,h=quality==="print"?3300:1100;
 if(raw?._blank||mod==="blank-page")return blankCanvas(quality);
 if(mod==="maze-studio"&&window.FenixMaze){const assets=await FenixMaze.prepareAssets(page);return FenixMaze.render(page,{solution,width:w,height:h,assetImages:assets}).canvas}
 if(mod==="word-search-studio"&&window.FenixWordSearch){const assets=await FenixWordSearch.prepareAssets(page);return FenixWordSearch.render(page,{solution,width:w,height:h,assetImages:assets}).canvas}
 if(mod==="coloring-studio"&&window.FenixColoring){const a=await FenixColoring.prepareAsset(page);return FenixColoring.render(page,{width:w,height:h,assetImage:a.image})}
 if(mod==="complete-picture"&&window.FenixCompletePicture){const o=FenixCompletePicture.optionsFromPage(page),ref=page.recipe?.content?.assetRef;let img=null;if(o.assetSource!=="built-in"&&ref){const a=FenixCore.getAsset(ref);if(a?.dataUrl)img=await loadImage(a.dataUrl)}return FenixCompletePicture.render(o,page.recipe?.seed,Number(page.recipe?.settings?.pageIndex)||0,{solution,scale:quality==="print"?3:1,customImage:img})}
 if(mod==="intro-studio"&&window.FenixIntroRenderer){const prepared=FenixIntroRenderer.prepare(page,{...project(),pages});return FenixIntroRenderer.render(prepared,{width:w,height:h})}
 if(ending.has(mod)&&window.FenixEndingRenderers){let qrAssetImage=null,creatorMarkImage=null;if(mod==="qr-studio"){const ref=page.recipe?.content?.assetRef||page.recipe?.settings?.qrAssetRef,a=ref?FenixCore.getAsset(ref):null;if(a?.dataUrl)qrAssetImage=await loadImage(a.dataUrl)}if(mod==="certificate-studio"){const ref=page.recipe?.content?.creatorMarkAssetRef||page.recipe?.settings?.creatorMarkAssetRef,a=ref?FenixCore.getAsset(ref):null;if(a?.dataUrl)creatorMarkImage=await loadImage(a.dataUrl)}return FenixEndingRenderers.render(page,{width:w,height:h,qrAssetImage,creatorMarkImage})}
 return storedCanvas(solution?(page.solution?.imageData||page.solutionImageData):(page.preview?.imageData||page.imageData),quality)
}
function fitTarget(source){const p=profile();if(source.width===p.width&&source.height===p.height)return source;const c=document.createElement("canvas");c.width=p.width;c.height=p.height;const x=c.getContext("2d");x.fillStyle="#fff";x.fillRect(0,0,c.width,c.height);const s=Math.min(c.width/source.width,c.height/source.height),w=source.width*s,h=source.height*s;x.drawImage(source,(c.width-w)/2,(c.height-h)/2,w,h);return c}
function pageNumber(c,n){if($("#pageNumbers").value!=="yes")return;c.getContext("2d").save();const x=c.getContext("2d"),fs=Math.max(28,Math.round(c.width/62));x.fillStyle="#444";x.font=`${fs}px Arial`;x.textAlign="center";x.fillText(String(n),c.width/2,c.height-Math.round(c.height*.018));x.restore()}
function ordered(source=pages,solutionPages=0){return window.FenixBookOrder?.compose?FenixBookOrder.compose(source,{solutionPageCount:solutionPages}):source}
function solutionEntries(source){return source.map((page,index)=>({page,pageNumber:index+1})).filter(x=>hasSolution(x.page))}
function sequence(){const include=$("#includeSolutions").value==="yes",clean=pages.filter(p=>!p?._autoParity),sorted=window.FenixBookOrder?.sort?FenixBookOrder.sort(clean):clean,solutions=include?solutionEntries(sorted):[],orderedPages=ordered(sorted,solutions.length),body=orderedPages.filter(p=>!ending.has(moduleOf(p))),closing=orderedPages.filter(p=>ending.has(moduleOf(p)));return{body,closing,solutions:include?solutionEntries(body):[]}}
async function solutionPage(entry){const c=fitTarget(await renderCanvas(entry.page,true,"print"));const x=c.getContext("2d");x.save();x.fillStyle="rgba(255,255,255,.94)";x.fillRect(0,0,c.width,Math.round(c.height*.07));x.fillStyle="#111";x.font=`700 ${Math.max(42,Math.round(c.width*.023))}px Arial`;x.textAlign="center";x.fillText(`${NAMES[moduleOf(entry.page)]||"Activity"} — rozwiązanie strony ${entry.pageNumber}`,c.width/2,Math.round(c.height*.045));x.restore();return c}
async function jpeg(c){const b=await new Promise(r=>c.toBlob(r,"image/jpeg",.93));if(!b)throw new Error("Nie udało się utworzyć obrazu strony PDF.");return new Uint8Array(await b.arrayBuffer())}
async function buildPdf(){const s=sequence(),all=[...s.body.map(p=>({type:"page",page:p})),...s.solutions.map(e=>({type:"solution",entry:e})),...s.closing.map(p=>({type:"page",page:p}))],p=profile(),out=[];for(let i=0;i<all.length;i++){progress.textContent=`Renderuję PDF: ${i+1} / ${all.length}`;let c=all[i].type==="solution"?await solutionPage(all[i].entry):fitTarget(await renderCanvas(all[i].page,false,"print"));pageNumber(c,i+1);out.push({jpegBytes:await jpeg(c),pixelWidth:c.width,pixelHeight:c.height,widthPt:p.width/p.dpi*72,heightPt:p.height/p.dpi*72});await new Promise(r=>requestAnimationFrame(r))}const bytes=FenixPdf.build({pages:out,title:$("#bookTitle").value||project().name});return FenixPdf.download(bytes,$("#bookTitle").value||project().name)}
function validate(){const missing=pages.filter(p=>!p?._blank&&!ending.has(moduleOf(p))&&!p.preview?.imageData&&!p.imageData&&!["maze-studio","word-search-studio","coloring-studio","complete-picture","intro-studio"].includes(moduleOf(p)));validation.textContent=pages.length?missing.length?`Uwaga: ${missing.length} stron nie ma jeszcze renderera/fallbacku w Book Builderze.`:`✓ Projekt gotowy do podglądu i eksportu PDF.`:"Projekt nie zawiera stron.";validation.className=`validation ${missing.length?"warn":"ok"}`}
async function thumb(card,page,token){try{const c=await renderCanvas(page,false,"preview");if(token!==renderToken||!card.isConnected)return;const img=document.createElement("img");img.src=c.toDataURL("image/jpeg",.78);card.querySelector(".thumb").replaceChildren(img)}catch(e){card.querySelector(".thumb").textContent="!"}}
function render(){const token=++renderToken;list.innerHTML="";empty.hidden=pages.length>0;$("#pageCount").textContent=`${pages.length} stron`;pages.forEach((p,i)=>{const card=document.createElement("article");card.className="page-card";card.draggable=true;card.innerHTML=`<span class="index">${i+1}</span><div class="thumb">…</div><div class="meta"><strong>${p.title||NAMES[moduleOf(p)]||"Strona"}</strong><small>${NAMES[moduleOf(p)]||moduleOf(p)}${hasSolution(p)?" · solution ✓":""}</small><div class="row"><button data-up="${i}">↑</button><button data-down="${i}">↓</button><button data-remove="${i}">Usuń</button></div></div>`;card.ondragstart=()=>dragIndex=i;card.ondragover=e=>e.preventDefault();card.ondrop=e=>{e.preventDefault();if(dragIndex==null||dragIndex===i)return;const[m]=pages.splice(dragIndex,1);pages.splice(i,0,m);dragIndex=null;render()};list.appendChild(card);thumb(card,p,token)});list.querySelectorAll("[data-up]").forEach(b=>b.onclick=()=>move(+b.dataset.up,-1));list.querySelectorAll("[data-down]").forEach(b=>b.onclick=()=>move(+b.dataset.down,1));list.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{pages.splice(+b.dataset.remove,1);render()});validate()}
function move(i,d){const j=i+d;if(j<0||j>=pages.length)return;[pages[i],pages[j]]=[pages[j],pages[i]];render()}
function load(){const p=project();pages=FenixCore.getCart().map((x,i)=>({...normalize(x),_builderId:x.id||`p-${i}`}));$("#bookTitle").value=p.name;$("#format").value=String(p.format||"8.5x11").toLowerCase()==="a4"?"a4":p.format||"8.5x11";$("#projectInfo").textContent=`Aktywny projekt: ${p.name} · ${pages.length} stron`;render()}
$("#autoOrder").onclick=()=>{const include=$("#includeSolutions").value==="yes",solutionPages=include?solutionEntries(pages).length:0;pages=ordered(pages,solutionPages);render();progress.textContent="✓ Uporządkowano: Intro → ćwiczenia → Solutions → Congratulations → QR → Certificate."};
$("#addBlank").onclick=()=>{const id=`blank-${Date.now()}`;pages.push({_blank:true,id,module:"blank-page",title:"Pusta strona",recipe:{module:"blank-page",settings:{},content:{}},solution:{available:false}});render()};
$("#refresh").onclick=load;
$("#preview").onclick=async()=>{if(!pages.length)return;previewGrid.innerHTML="";const s=sequence(),all=[...s.body,...s.closing];progress.textContent="Generuję podgląd…";for(let i=0;i<all.length;i++){const c=await renderCanvas(all[i],false,"preview"),img=document.createElement("img");img.src=c.toDataURL("image/jpeg",.76);img.alt=`Strona ${i+1}`;previewGrid.appendChild(img)}progress.textContent=`✓ Podgląd gotowy · ${all.length} stron głównych${s.solutions.length?` + ${s.solutions.length} rozwiązań`:""}.`};
$("#exportPdf").onclick=async()=>{if(!pages.length)return;const btn=$("#exportPdf");btn.disabled=true;try{const r=await buildPdf();progress.textContent=`✓ PDF gotowy: ${r.fileName} · ${(r.size/1024/1024).toFixed(1)} MB`;}catch(e){console.error(e);progress.textContent=`Błąd PDF: ${e.message||e}`;}finally{btn.disabled=false}};
["format","pageNumbers","includeSolutions"].forEach(id=>$("#"+id).addEventListener("change",validate));load();
})();