import{CartManager}from"../core/cart.js";
import{createRecipe,normalizeRecipe}from"../core/recipe.js";

export function createColoringStudio({onCartChange=()=>{},onSaved=()=>{}}={}){
  const canvas=document.querySelector("#coloringCanvas"),ctx=canvas.getContext("2d"),fileInput=document.querySelector("#coloringFile"),titleInput=document.querySelector("#coloringTitle"),scaleInput=document.querySelector("#coloringScale"),xInput=document.querySelector("#coloringX"),yInput=document.querySelector("#coloringY"),status=document.querySelector("#coloringStatus"),addButton=document.querySelector("#addColoringToCart");
  let image=null,imageData="",editingPageId=null;
  function draw(){ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#111827";ctx.textAlign="center";ctx.font="700 42px Arial";ctx.fillText(titleInput.value.trim()||"Color the Picture!",canvas.width/2,82);if(!image){ctx.fillStyle="#94a3b8";ctx.font="600 28px Arial";ctx.fillText("Dodaj obrazek SVG lub PNG",canvas.width/2,canvas.height/2);return}const scale=Number(scaleInput.value)/100,maxW=canvas.width*.72,maxH=canvas.height*.72,ratio=Math.min(maxW/image.width,maxH/image.height)*scale,w=image.width*ratio,h=image.height*ratio,x=(canvas.width-w)/2+Number(xInput.value),y=160+(canvas.height-230-h)/2+Number(yInput.value);ctx.drawImage(image,x,y,w,h)}
  function loadImage(data,done=()=>{}){const img=new Image();img.onload=()=>{image=img;imageData=data;draw();done()};img.onerror=()=>{status.textContent="Nie udało się wczytać obrazka"};img.src=data}
  fileInput.onchange=()=>{const file=fileInput.files?.[0];if(!file)return;if(!/image\/(png|svg\+xml)/.test(file.type)){status.textContent="Wybierz plik PNG lub SVG";return}const reader=new FileReader();reader.onload=()=>loadImage(String(reader.result),()=>status.textContent=editingPageId?"Nowy obrazek wczytany — zapisz zmiany":"Obrazek wczytany");reader.readAsDataURL(file)};
  ;[titleInput,scaleInput,xInput,yInput].forEach(input=>input.oninput=draw);
  addButton.onclick=()=>{if(!imageData){status.textContent="Najpierw dodaj obrazek";return}const recipe=createRecipe({module:"coloring-studio",title:titleInput.value.trim()||"Coloring Page",asset:{type:"data-url",data:imageData},settings:{scale:Number(scaleInput.value),x:Number(xInput.value),y:Number(yInput.value)}});if(editingPageId){CartManager.update(editingPageId,recipe);status.textContent="Zmiany zapisane — podgląd Koszyka odświeżony";editingPageId=null;addButton.textContent="Dodaj do Koszyka Feniksa";onCartChange();onSaved()}else{CartManager.add(recipe);status.textContent="Dodano do Koszyka";onCartChange()}};
  function loadRecipe(page){const recipe=normalizeRecipe(page);if(recipe.module!=="coloring-studio"||!recipe.asset?.data)return false;editingPageId=page.id;titleInput.value=recipe.title||"Color the Picture!";scaleInput.value=recipe.settings?.scale??100;xInput.value=recipe.settings?.x??0;yInput.value=recipe.settings?.y??0;loadImage(recipe.asset.data,()=>{status.textContent="Edytujesz stronę z Koszyka";addButton.textContent="Zapisz zmiany"});return true}
  draw();return{draw,loadRecipe};
}