import{CartManager}from"../core/cart.js";
import{createRecipe,normalizeRecipe}from"../core/recipe.js";

const SET_LABELS={shapes:"Kształty",numbers:"Liczby",letters:"Litery",mixed:"Mieszany"};
function makeSeed(){return(Date.now()+Math.floor(Math.random()*1e9))>>>0}
function mulberry32(seed){return function(){let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function shuffle(items,random){const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}
function symbolPool(set){if(set==="numbers")return["1","2","3","4","5","6","7","8","9"];if(set==="letters")return["A","B","C","D","E","F","G","H"];if(set==="mixed")return["circle","triangle","square","star","1","2","A","B"];return["circle","triangle","square","star","diamond","plus"]}
function drawStar(ctx,x,y,r){ctx.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,rr=i%2?r*.43:r,px=x+Math.cos(a)*rr,py=y+Math.sin(a)*rr;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath();ctx.stroke()}
function drawSymbol(ctx,symbol,x,y,size){ctx.save();ctx.strokeStyle="#111827";ctx.fillStyle="#111827";ctx.lineWidth=Math.max(2,size*.08);ctx.lineJoin="round";ctx.lineCap="round";if(symbol==="circle"){ctx.beginPath();ctx.arc(x,y,size*.38,0,Math.PI*2);ctx.stroke()}else if(symbol==="triangle"){ctx.beginPath();ctx.moveTo(x,y-size*.42);ctx.lineTo(x+size*.4,y+size*.34);ctx.lineTo(x-size*.4,y+size*.34);ctx.closePath();ctx.stroke()}else if(symbol==="square"){ctx.strokeRect(x-size*.34,y-size*.34,size*.68,size*.68)}else if(symbol==="diamond"){ctx.beginPath();ctx.moveTo(x,y-size*.43);ctx.lineTo(x+size*.38,y);ctx.lineTo(x,y+size*.43);ctx.lineTo(x-size*.38,y);ctx.closePath();ctx.stroke()}else if(symbol==="plus"){ctx.beginPath();ctx.moveTo(x-size*.36,y);ctx.lineTo(x+size*.36,y);ctx.moveTo(x,y-size*.36);ctx.lineTo(x,y+size*.36);ctx.stroke()}else if(symbol==="star")drawStar(ctx,x,y,size*.43);else{ctx.textAlign="center";ctx.textBaseline="middle";ctx.font=`700 ${size*.72}px Arial`;ctx.fillText(symbol,x,y+size*.03)}ctx.restore()}
function makePuzzle(random,set,difficulty){const pool=shuffle(symbolPool(set),random),patternLength=difficulty==="easy"?2:difficulty==="medium"?3:4,pattern=pool.slice(0,patternLength),slots=difficulty==="easy"?5:6,sequence=Array.from({length:slots},(_,i)=>pattern[i%pattern.length]),answer=sequence[sequence.length-1],wrong=shuffle(pool.filter(x=>x!==answer),random).slice(0,2),options=shuffle([answer,...wrong],random);return{sequence,answer,options}}
function optionBox(ctx,x,y,size,radius){ctx.beginPath();if(typeof ctx.roundRect==="function")ctx.roundRect(x-size*.52,y-size*.52,size*1.04,size*1.04,radius);else ctx.rect(x-size*.52,y-size*.52,size*1.04,size*1.04);ctx.stroke()}
export function drawLogicPage(canvas,page){const ctx=canvas.getContext("2d"),w=canvas.width,h=canvas.height,s=w/900,settings=page.settings||{},rows=Math.max(2,Math.min(7,Number(settings.rows)||4)),set=settings.set||"shapes",difficulty=settings.difficulty||"medium",random=mulberry32(Number(page.seed)||1),margin=58*s,top=145*s,bottom=55*s,rowH=(h-top-bottom)/rows;ctx.fillStyle="#fff";ctx.fillRect(0,0,w,h);ctx.fillStyle="#111827";ctx.textAlign="center";ctx.textBaseline="alphabetic";ctx.font=`700 ${42*s}px Arial`;ctx.fillText(page.title||"What Comes Next?",w/2,78*s);ctx.font=`500 ${18*s}px Arial`;ctx.fillStyle="#64748b";ctx.fillText("Look at the pattern and circle the correct answer.",w/2,112*s);for(let row=0;row<rows;row++){const puzzle=makePuzzle(random,set,difficulty),cy=top+rowH*(row+.5),seqW=w*.58,startX=margin,slot=(seqW-margin)/puzzle.sequence.length,size=Math.min(58*s,rowH*.34);ctx.strokeStyle="#cbd5e1";ctx.lineWidth=2*s;ctx.beginPath();ctx.moveTo(margin,cy+rowH*.34);ctx.lineTo(w-margin,cy+rowH*.34);ctx.stroke();puzzle.sequence.forEach((symbol,i)=>{const x=startX+slot*(i+.5);if(i===puzzle.sequence.length-1){ctx.save();ctx.strokeStyle="#94a3b8";ctx.setLineDash([7*s,6*s]);ctx.strokeRect(x-size*.48,cy-size*.48,size*.96,size*.96);ctx.setLineDash([]);ctx.fillStyle="#64748b";ctx.font=`700 ${size*.72}px Arial`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("?",x,cy);ctx.restore()}else drawSymbol(ctx,symbol,x,cy,size)});const optionsX=w*.69,optionGap=72*s;puzzle.options.forEach((symbol,i)=>{const x=optionsX+i*optionGap;ctx.save();ctx.strokeStyle="#94a3b8";ctx.lineWidth=2*s;optionBox(ctx,x,cy,size,10*s);ctx.restore();drawSymbol(ctx,symbol,x,cy,size*.72)})}}
export function createLogicStudio({onCartChange=()=>{}}={}){const canvas=document.querySelector("#logicCanvas"),title=document.querySelector("#logicTitle"),set=document.querySelector("#logicSet"),rows=document.querySelector("#logicRows"),difficulty=document.querySelector("#logicDifficulty"),status=document.querySelector("#logicStatus"),add=document.querySelector("#addLogicToCart"),variant=document.querySelector("#newLogicVariant");let seed=makeSeed(),editingPageId=null;function recipe(){return createRecipe({module:"logic-studio",title:title.value.trim()||"What Comes Next?",seed,settings:{set:set.value,rows:Number(rows.value),difficulty:difficulty.value}})}function draw(){drawLogicPage(canvas,recipe());status.textContent=`${SET_LABELS[set.value]||set.value} · seed ${seed}`}function reset(){editingPageId=null;add.textContent="Dodaj do Koszyka Feniksa"}variant.onclick=()=>{reset();seed=makeSeed();draw()};[title,set,rows,difficulty].forEach(input=>input.oninput=draw);add.onclick=()=>{const r=recipe();if(editingPageId){CartManager.update(editingPageId,r);status.textContent="Zmiany zapisane w Koszyku";reset()}else{CartManager.add(r);status.textContent="Dodano do Koszyka"}onCartChange()};function loadRecipe(page){const r=normalizeRecipe(page);if(r.module!=="logic-studio")return false;editingPageId=page.id;seed=Number(r.seed)||makeSeed();title.value=r.title||"What Comes Next?";set.value=r.settings?.set||"shapes";rows.value=r.settings?.rows??4;difficulty.value=r.settings?.difficulty||"medium";add.textContent="Zapisz zmiany w Koszyku";draw();status.textContent="Edytujesz stronę z Koszyka";return true}draw();return{draw,loadRecipe}}
