export function mulberry32(seed){return function(){let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}

function boundaryPoints(cols,rows){const points=[];for(let x=0;x<cols;x++){points.push({x,y:0,wall:0,side:"top"});points.push({x,y:rows-1,wall:2,side:"bottom"})}for(let y=0;y<rows;y++){points.push({x:0,y,wall:3,side:"left"});points.push({x:cols-1,y,wall:1,side:"right"})}return points}

function chooseEndpoints(cols,rows,seed){const random=mulberry32((seed^0x9E3779B9)>>>0),points=boundaryPoints(cols,rows),start=points[Math.floor(random()*points.length)];let candidates=points.filter(point=>point.side!==start.side&&Math.abs(point.x-start.x)+Math.abs(point.y-start.y)>=Math.floor((cols+rows)/3));if(!candidates.length)candidates=points.filter(point=>point.side!==start.side);const end=candidates[Math.floor(random()*candidates.length)];return{start,end}}

export function buildMaze(cols,rows,seed,savedEndpoints){const random=mulberry32(seed),cells=Array.from({length:rows},()=>Array.from({length:cols},()=>({v:false,w:[true,true,true,true]}))),endpoints=savedEndpoints?.start&&savedEndpoints?.end?savedEndpoints:chooseEndpoints(cols,rows,seed),stack=[[endpoints.start.x,endpoints.start.y]],dirs=[[0,-1,0,2],[1,0,1,3],[0,1,2,0],[-1,0,3,1]];cells[endpoints.start.y][endpoints.start.x].v=true;while(stack.length){const[x,y]=stack[stack.length-1],choices=[];for(const[dx,dy,wall,opposite]of dirs){const nx=x+dx,ny=y+dy;if(nx>=0&&ny>=0&&nx<cols&&ny<rows&&!cells[ny][nx].v)choices.push([nx,ny,wall,opposite])}if(!choices.length){stack.pop();continue}const[nx,ny,wall,opposite]=choices[Math.floor(random()*choices.length)];cells[y][x].w[wall]=false;cells[ny][nx].w[opposite]=false;cells[ny][nx].v=true;stack.push([nx,ny])}cells[endpoints.start.y][endpoints.start.x].w[endpoints.start.wall]=false;cells[endpoints.end.y][endpoints.end.x].w[endpoints.end.wall]=false;return{cols,rows,cells,seed,start:endpoints.start,end:endpoints.end}}

export function solveMaze(maze){const{cols,rows,cells,start,end}=maze,q=[[start.x,start.y]],seen=new Set([`${start.x},${start.y}`]),prev=new Map(),dirs=[[0,-1,0],[1,0,1],[0,1,2],[-1,0,3]];while(q.length){const[x,y]=q.shift();if(x===end.x&&y===end.y)break;for(const[dx,dy,wall]of dirs){const nx=x+dx,ny=y+dy,key=`${nx},${ny}`;if(nx>=0&&ny>=0&&nx<cols&&ny<rows&&!cells[y][x].w[wall]&&!seen.has(key)){seen.add(key);prev.set(key,[x,y]);q.push([nx,ny])}}}const path=[];let cur=[end.x,end.y];while(cur){path.push(cur);if(cur[0]===start.x&&cur[1]===start.y)break;cur=prev.get(`${cur[0]},${cur[1]}`)}return path.reverse()}

export function drawEndpointMarkers(ctx,maze,startX,startY,cell,compact=false){const radius=Math.max(compact?2.5:8,cell*(compact?.18:.22));for(const[item,label,fill]of[[maze.start,"S","#16a34a"],[maze.end,"M","#ef4444"]]){const x=startX+(item.x+.5)*cell,y=startY+(item.y+.5)*cell;ctx.save();ctx.fillStyle=fill;ctx.beginPath();ctx.arc(x,y,radius,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.textAlign="center";ctx.textBaseline="middle";ctx.font=`700 ${Math.max(compact?5:13,radius*1.15)}px Arial`;ctx.fillText(label,x,y+.5);ctx.restore()}}
