import{CartManager}from"../core/cart.js";
import{createRecipe,normalizeRecipe}from"../core/recipe.js";
import{buildMaze,solveMaze,drawEndpointMarkers}from"./maze-engine.js";
import{buildThemeDecorations,drawMazeTheme,normalizeTheme}from"./maze-themes.js";

function clampInt(v,min,max,fallback){const n=parseInt(v,10);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):fallback}

export function createMazeStudio({onCartChange=()=>{}}={}){
 const canvas=document.querySelector("#mazeCanvas"),ctx=canvas.getContext("2d"),colsInput=document.querySelector("#cols"),rowsInput=document.querySelector("#rows"),lineWidthInput=document.querySelector("#lineWidth"),titleInput=document.querySelector("#pageTitle"),statusEl=document.querySelector("#mazeStatus"),seedLabel=document.querySelector("#seedLabel"),addButton=document.querySelector("#addMazeToCart"),solutionInput=document.querySelector("#showSolution"),themeInput=document.querySelector("#mazeTheme"),assetCountInput=document.querySelector("#mazeAssetCount");let currentSeed=Date.now()>>>0,currentMaze=null,currentDecorations=[],editingPageId=null;
 function theme(){return normalizeTheme(themeInput?.value)}
 function assetCount(){return clampInt(assetCountInput?.value,0,10,6)}
 function draw(){if(!currentMaze)return;const{cols,rows,cells}=currentMaze,marginX=80,top=170,bottom=90,areaW=canvas.width-marginX*2,areaH=canvas.height-top-bottom,cell=Math.min(areaW/cols,areaH/rows),mazeW=cell*cols,mazeH=cell*rows,startX=(canvas.width-mazeW)/2,startY=top+(areaH-mazeH)/2;ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#111827";ctx.textAlign="center";ctx.font="700 42px Arial";ctx.fillText(titleInput.value.trim()||"Find the Way!",canvas.width/2,82);drawMazeTheme(ctx,{maze:currentMaze,startX,startY,cell,canvasWidth:canvas.width,canvasHeight:canvas.height,theme:theme(),decorations:currentDecorations});ctx.strokeStyle="#111827";ctx.lineWidth=Number(lineWidthInput.value);ctx.beginPath();for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const px=startX+x*cell,py=startY+y*cell,w=cells[y][x].w;if(w[0]){ctx.moveTo(px,py);ctx.lineTo(px+cell,py)}if(w[1]){ctx.moveTo(px+cell,py);ctx.lineTo(px+cell,py+cell)}if(w[2]){ctx.moveTo(px,py+cell);ctx.lineTo(px+cell,py+cell)}if(w[3]){ctx.moveTo(px,py);ctx.lineTo(px,py+cell)}}ctx.stroke();if(theme()==="classic")drawEndpointMarkers(ctx,currentMaze,startX,startY,cell);else drawMazeTheme(ctx,{maze:currentMaze,startX,startY,cell,canvasWidth:canvas.width,canvasHeight:canvas.height,theme:theme(),decorations:[]});if(solutionInput.checked){const path=solveMaze(currentMaze);ctx.save();ctx.strokeStyle="#ef4444";ctx.globalAlpha=.72;ctx.lineWidth=Math.max(5,cell*.22);ctx.lineCap="round";ctx.lineJoin="round";ctx.beginPath();path.forEach(([x,y],i)=>{const px=startX+(x+.5)*cell,py=startY+(y+.5)*cell;i?ctx.lineTo(px,py):ctx.moveTo(px,py)});ctx.stroke();ctx.restore();theme()==="classic"?drawEndpointMarkers(ctx,currentMaze,startX,startY,cell):drawMazeTheme(ctx,{maze:currentMaze,startX,startY,cell,canvasWidth:canvas.width,canvasHeight:canvas.height,theme:theme(),decorations:[]})}}
 function regenerate(newSeed=true,endpoints,savedDecorations){const cols=clampInt(colsInput.value,6,45,18),rows=clampInt(rowsInput.value,8,58,24);if(newSeed)currentSeed=(Date.now()+Math.floor(Math.random()*1e9))>>>0;currentMaze=buildMaze(cols,rows,currentSeed,endpoints);currentDecorations=Array.isArray(savedDecorations)?savedDecorations:buildThemeDecorations({seed:currentSeed,theme:theme(),count:assetCount()});draw();seedLabel.textContent=`Seed: ${currentSeed}`;statusEl.textContent=`Start: ${currentMaze.start.side} · Meta: ${currentMaze.end.side} · Motyw: ${themeInput.options[themeInput.selectedIndex]?.text||theme()}`}
 function resetEditing(){editingPageId=null;addButton.textContent="Dodaj do Koszyka Feniksa"}
 function loadRecipe(page){const recipe=normalizeRecipe(page);if(recipe.module!=="maze-studio")return false;editingPageId=page.id;currentSeed=Number(recipe.seed)>>>0;colsInput.value=recipe.settings?.cols||18;rowsInput.value=recipe.settings?.rows||24;lineWidthInput.value=recipe.settings?.lineWidth||5;titleInput.value=recipe.title||"Find the Way!";themeInput.value=normalizeTheme(recipe.settings?.theme);assetCountInput.value=recipe.settings?.assetCount??6;solutionInput.checked=false;regenerate(false,recipe.settings?.endpoints,recipe.settings?.decorations);statusEl.textContent="Edytujesz stronę z Koszyka";addButton.textContent="Zapisz zmiany w Koszyku";return true}
 document.querySelectorAll("[data-difficulty]").forEach(button=>button.onclick=()=>{const presets={easy:[10,14,7],medium:[18,24,5],hard:[28,38,3]},[cols,rows,width]=presets[button.dataset.difficulty];colsInput.value=cols;rowsInput.value=rows;lineWidthInput.value=width;document.querySelectorAll("[data-difficulty]").forEach(x=>x.classList.toggle("active",x===button));resetEditing();regenerate(true)});
 document.querySelector("#newVariant").onclick=()=>{resetEditing();regenerate(true)};document.querySelector("#duplicateMaze").onclick=()=>{draw();statusEl.textContent="Ten sam układ, motyw i assety zachowane"};document.querySelector("#downloadMaze").onclick=()=>{const a=document.createElement("a");a.download=`fenix-maze-${currentSeed}.png`;a.href=canvas.toDataURL("image/png");a.click()};solutionInput.onchange=draw;themeInput.onchange=()=>{resetEditing();currentDecorations=buildThemeDecorations({seed:currentSeed,theme:theme(),count:assetCount()});draw()};assetCountInput.oninput=()=>{resetEditing();currentDecorations=buildThemeDecorations({seed:currentSeed,theme:theme(),count:assetCount()});draw()};
 addButton.onclick=()=>{const recipe=createRecipe({module:"maze-studio",title:titleInput.value.trim()||"Maze",seed:currentSeed,settings:{cols:currentMaze.cols,rows:currentMaze.rows,lineWidth:Number(lineWidthInput.value),endpoints:{start:currentMaze.start,end:currentMaze.end},theme:theme(),assetCount:assetCount(),decorations:currentDecorations}});if(editingPageId){CartManager.update(editingPageId,recipe);statusEl.textContent="Zmiany zapisane w Koszyku";resetEditing()}else{CartManager.add(recipe);statusEl.textContent="Dodano do Koszyka"}onCartChange()};[colsInput,rowsInput].forEach(input=>input.onchange=()=>{resetEditing();regenerate(true)});lineWidthInput.oninput=draw;titleInput.oninput=draw;regenerate(false);return{regenerate,draw,loadRecipe,resetEditing}
}
