import{CartManager}from"../core/cart.js";

function mulberry32(seed){return function(){let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function clampInt(v,min,max,fallback){const n=parseInt(v,10);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):fallback}
function buildMaze(cols,rows,seed){const random=mulberry32(seed),cells=Array.from({length:rows},()=>Array.from({length:cols},()=>({v:false,w:[true,true,true,true]}))),stack=[[0,0]],dirs=[[0,-1,0,2],[1,0,1,3],[0,1,2,0],[-1,0,3,1]];cells[0][0].v=true;while(stack.length){const[x,y]=stack[stack.length-1],choices=[];for(const[dx,dy,wall,opposite]of dirs){const nx=x+dx,ny=y+dy;if(nx>=0&&ny>=0&&nx<cols&&ny<rows&&!cells[ny][nx].v)choices.push([nx,ny,wall,opposite])}if(!choices.length){stack.pop();continue}const[nx,ny,wall,opposite]=choices[Math.floor(random()*choices.length)];cells[y][x].w[wall]=false;cells[ny][nx].w[opposite]=false;cells[ny][nx].v=true;stack.push([nx,ny])}cells[0][0].w[3]=false;cells[rows-1][cols-1].w[1]=false;return{cols,rows,cells,seed}}

export function createMazeStudio({onCartChange=()=>{}}={}){
  const canvas=document.querySelector("#mazeCanvas"),ctx=canvas.getContext("2d"),colsInput=document.querySelector("#cols"),rowsInput=document.querySelector("#rows"),lineWidthInput=document.querySelector("#lineWidth"),titleInput=document.querySelector("#pageTitle"),statusEl=document.querySelector("#mazeStatus"),seedLabel=document.querySelector("#seedLabel");
  let currentSeed=Date.now()>>>0,currentMaze=null;
  function draw(){if(!currentMaze)return;const{cols,rows,cells}=currentMaze,marginX=80,top=170,bottom=90,areaW=canvas.width-marginX*2,areaH=canvas.height-top-bottom,cell=Math.min(areaW/cols,areaH/rows),mazeW=cell*cols,mazeH=cell*rows,startX=(canvas.width-mazeW)/2,startY=top+(areaH-mazeH)/2;ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#111827";ctx.textAlign="center";ctx.font="700 42px Arial";ctx.fillText(titleInput.value.trim()||"Find the Way!",canvas.width/2,82);ctx.strokeStyle="#111827";ctx.lineWidth=Number(lineWidthInput.value);ctx.beginPath();for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const px=startX+x*cell,py=startY+y*cell,w=cells[y][x].w;if(w[0]){ctx.moveTo(px,py);ctx.lineTo(px+cell,py)}if(w[1]){ctx.moveTo(px+cell,py);ctx.lineTo(px+cell,py+cell)}if(w[2]){ctx.moveTo(px,py+cell);ctx.lineTo(px+cell,py+cell)}if(w[3]){ctx.moveTo(px,py);ctx.lineTo(px,py+cell)}}ctx.stroke()}
  function regenerate(newSeed=true){const cols=clampInt(colsInput.value,6,45,18),rows=clampInt(rowsInput.value,8,58,24);if(newSeed)currentSeed=(Date.now()+Math.floor(Math.random()*1e9))>>>0;currentMaze=buildMaze(cols,rows,currentSeed);draw();seedLabel.textContent=`Seed: ${currentSeed}`;statusEl.textContent="Labirynt wygenerowany"}
  document.querySelector("#newVariant").onclick=()=>regenerate(true);
  document.querySelector("#duplicateMaze").onclick=()=>{draw();statusEl.textContent="Ten sam układ zachowany"};
  document.querySelector("#downloadMaze").onclick=()=>{const a=document.createElement("a");a.download=`fenix-maze-${currentSeed}.png`;a.href=canvas.toDataURL("image/png");a.click()};
  document.querySelector("#addMazeToCart").onclick=()=>{CartManager.add({module:"maze-studio",title:titleInput.value.trim()||"Maze",seed:currentSeed,settings:{cols:currentMaze.cols,rows:currentMaze.rows,lineWidth:Number(lineWidthInput.value)}});statusEl.textContent="Dodano do Koszyka";onCartChange()};
  ;[colsInput,rowsInput].forEach(input=>input.onchange=()=>regenerate(true));lineWidthInput.oninput=draw;titleInput.oninput=draw;regenerate(false);
  return{regenerate,draw};
}