import{CartManager}from"../core/cart.js";
import{createRecipe,normalizeRecipe}from"../core/recipe.js";

const PATTERNS={straight:"Linie proste",wave:"Fale",zigzag:"Zygzak",loops:"Pętle",mountains:"Góry",mixed:"Mieszany"};
function makeSeed(){return(Date.now()+Math.floor(Math.random()*1e9))>>>0}
function mulberry32(seed){return function(){let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function pathFor(type,x1,x2,y,amp,step,random){if(type==="straight")return`M ${x1} ${y} L ${x2} ${y}`;if(type==="wave"){let d=`M ${x1} ${y}`;for(let x=x1;x<x2;x+=step)d+=` Q ${x+step/4} ${y-amp} ${x+step/2} ${y} Q ${x+step*.75} ${y+amp} ${Math.min(x+step,x2)} ${y}`;return d}if(type==="zigzag"||type==="mountains"){let d=`M ${x1} ${y}`,up=true;for(let x=x1+step/2;x<x2;x+=step/2){d+=` L ${x} ${y+(up?-amp:amp)}`;up=!up}return d+` L ${x2} ${y}`}if(type==="loops"){let d=`M ${x1} ${y}`;for(let x=x1;x<x2;x+=step)d+=` C ${x+step*.2} ${y-amp} ${x+step*.8} ${y-amp} ${x+step} ${y} C ${x+step*.8} ${y+amp} ${x+step*.2} ${y+amp} ${x} ${y}`;return d}const options=["straight","wave","zigzag","loops","mountains"];return pathFor(options[Math.floor(random()*options.length)],x1,x2,y,amp,step,random)}
export function drawTracingPage(canvas,page){const ctx=canvas.getContext("2d"),w=canvas.width,h=canvas.height,s=w/900,settings=page.settings||{},rows=Math.max(2,Math.min(10,Number(settings.rows)||5)),pattern=settings.pattern||"wave",difficulty=settings.difficulty||"medium",seed=Number(page.seed)||1,random=mulberry32(seed),margin=80*s,top=150*s,bottom=80*s,gap=(h-top-bottom)/rows,amp=({easy:28,medium:42,hard:58}[difficulty]||42)*s,step=({easy:150,medium:110,hard:80}[difficulty]||110)*s;ctx.fillStyle="#fff";ctx.fillRect(0,0,w,h);ctx.fillStyle="#111827";ctx.textAlign="center";ctx.font=`700 ${42*s}px Arial`;ctx.fillText(page.title||"Trace the Lines!",w/2,80*s);ctx.lineWidth=Math.max(2,4*s);ctx.lineCap="round";ctx.setLineDash([12*s,10*s]);for(let i=0;i<rows;i++){const y=top+gap*(i+.5);ctx.strokeStyle="#94a3b8";ctx.beginPath();const p=new Path2D(pathFor(pattern,margin,w-margin,y,amp,step,random));ctx.stroke(p);ctx.fillStyle="#16a34a";ctx.beginPath();ctx.arc(margin,y,10*s,0,Math.PI*2);ctx.fill();ctx.fillStyle="#ef4444";ctx.beginPath();ctx.arc(w-margin,y,10*s,0,Math.PI*2);ctx.fill()}ctx.setLineDash([])}
export function createTracingStudio({onCartChange=()=>{}}={}){const canvas=document.querySelector("#tracingCanvas"),title=document.querySelector("#tracingTitle"),pattern=document.querySelector("#tracingPattern"),rows=document.querySelector("#tracingRows"),difficulty=document.querySelector("#tracingDifficulty"),status=document.querySelector("#tracingStatus"),add=document.querySelector("#addTracingToCart"),variant=document.querySelector("#newTracingVariant");let seed=makeSeed(),editingPageId=null;function recipe(){return createRecipe({module:"tracing-studio",title:title.value.trim()||"Trace the Lines!",seed,settings:{pattern:pattern.value,rows:Number(rows.value),difficulty:difficulty.value}})}function draw(){drawTracingPage(canvas,recipe());status.textContent=`${PATTERNS[pattern.value]||pattern.value} · seed ${seed}`}function reset(){editingPageId=null;add.textContent="Dodaj do Koszyka Feniksa"}variant.onclick=()=>{reset();seed=makeSeed();draw()};[title,pattern,rows,difficulty].forEach(x=>x.oninput=draw);add.onclick=()=>{const r=recipe();if(editingPageId){CartManager.update(editingPageId,r);status.textContent="Zmiany zapisane w Koszyku";reset()}else{CartManager.add(r);status.textContent="Dodano do Koszyka"}onCartChange()};function loadRecipe(page){const r=normalizeRecipe(page);if(r.module!=="tracing-studio")return false;editingPageId=page.id;seed=Number(r.seed)||makeSeed();title.value=r.title||"Trace the Lines!";pattern.value=r.settings?.pattern||"wave";rows.value=r.settings?.rows??5;difficulty.value=r.settings?.difficulty||"medium";add.textContent="Zapisz zmiany w Koszyku";draw();status.textContent="Edytujesz stronę z Koszyka";return true}draw();return{draw,loadRecipe}}
